"""League and team aliases plus resolver functions.

The TEAM_REGISTRY is generated by scripts/harvest_teams.py and lives in
teams_data.py. This module owns the LEAGUE_REGISTRY and the resolve_* functions.
Types (LeagueInfo, TeamInfo) live in sports_mcp._types to avoid circular imports.
"""

from __future__ import annotations

import difflib
from dataclasses import dataclass

from sports_mcp._types import LeagueInfo, TeamInfo

LEAGUE_REGISTRY: list[LeagueInfo] = [
    LeagueInfo(
        name="NFL",
        sport="football",
        slug="football/nfl",
        aliases=("nfl", "national football league"),
    ),
    LeagueInfo(
        name="NBA",
        sport="basketball",
        slug="basketball/nba",
        aliases=("nba", "national basketball association"),
    ),
    LeagueInfo(
        name="MLB",
        sport="baseball",
        slug="baseball/mlb",
        aliases=("mlb", "major league baseball"),
    ),
    LeagueInfo(
        name="NHL",
        sport="hockey",
        slug="hockey/nhl",
        aliases=("nhl", "national hockey league"),
    ),
    LeagueInfo(
        name="Premier League",
        sport="soccer",
        slug="soccer/eng.1",
        aliases=(
            "epl",
            "premier league",
            "english premier league",
            "the premier league",
        ),
    ),
    LeagueInfo(
        name="MLS",
        sport="soccer",
        slug="soccer/usa.1",
        aliases=("mls", "major league soccer"),
    ),
    LeagueInfo(
        name="World Cup",
        sport="soccer",
        slug="soccer/fifa.world",
        aliases=("world cup", "fifa world cup", "the world cup"),
    ),
    LeagueInfo(
        name="Champions League",
        sport="soccer",
        slug="soccer/uefa.champions",
        aliases=(
            "ucl",
            "champions league",
            "uefa champions league",
            "the champions league",
        ),
    ),
]


def _build_league_index() -> dict[str, LeagueInfo]:
    index: dict[str, LeagueInfo] = {}
    for li in LEAGUE_REGISTRY:
        for alias in li.aliases:
            index[alias] = li
        index[li.name.lower()] = li
    return index


LEAGUES: dict[str, LeagueInfo] = _build_league_index()


def resolve_league(text: str) -> LeagueInfo | None:
    """Resolve a free-text league name to a LeagueInfo, or None."""
    return LEAGUES.get(text.strip().lower())


from sports_mcp.teams_data import TEAM_REGISTRY  # noqa: E402, I001  (late import avoids circular dep — see module docstring)


@dataclass(frozen=True)
class TeamMatchOne:
    """Exactly one team matched."""

    team: TeamInfo


@dataclass(frozen=True)
class TeamMatchAmbiguous:
    """Multiple teams matched the alias."""

    teams: tuple[TeamInfo, ...]


@dataclass(frozen=True)
class TeamMatchNone:
    """No team matched. May include fuzzy suggestions."""

    suggestions: list[str]


TeamMatch = TeamMatchOne | TeamMatchAmbiguous | TeamMatchNone


def _build_team_index() -> dict[str, list[TeamInfo]]:
    """Build the alias -> [TeamInfo] index, deduplicating by (sport, espn_id).

    ESPN reuses numeric IDs across different sports (e.g. espn_id '13' is both
    the Las Vegas Raiders and the Los Angeles Lakers). However, within the same
    sport, a club like Arsenal shares the same espn_id in soccer/eng.1 (EPL)
    and soccer/uefa.champions (UCL). Only the first occurrence per sport is
    kept. Because LEAGUE_REGISTRY lists domestic leagues (EPL, MLS) before
    tournament leagues (UCL, World Cup), the domestic entry wins.
    """
    seen_sport_ids: set[tuple[str, str]] = set()
    index: dict[str, list[TeamInfo]] = {}
    for t in TEAM_REGISTRY:
        sport = t.league_slug.split("/")[0]
        key = (sport, t.espn_id)
        if key in seen_sport_ids:
            continue
        seen_sport_ids.add(key)
        for alias in t.aliases:
            index.setdefault(alias, []).append(t)
    return index


TEAMS: dict[str, list[TeamInfo]] = _build_team_index()


def _all_alias_strings() -> list[str]:
    return list(TEAMS.keys())


def resolve_team(
    text: str,
    prefer_league: str | None = None,
) -> TeamMatch:
    """Resolve a free-text team name to a TeamMatch.

    If multiple teams share the alias and prefer_league disambiguates,
    return the unique match in that league. Otherwise return ambiguous.

    For unknown aliases, return TeamMatchNone with up to three close
    suggestions via difflib.
    """
    key = text.strip().lower()
    matches = TEAMS.get(key, [])

    if prefer_league is not None and matches:
        in_league = [t for t in matches if t.league_slug == prefer_league]
        if len(in_league) == 1:
            return TeamMatchOne(in_league[0])

    if len(matches) == 1:
        return TeamMatchOne(matches[0])
    if len(matches) > 1:
        return TeamMatchAmbiguous(tuple(matches))

    suggestions = difflib.get_close_matches(key, _all_alias_strings(), n=3, cutoff=0.6)
    return TeamMatchNone(list(suggestions))
