"""Auto-generated team registry. Edit scripts/harvest_teams.py and re-run."""
from sports_mcp.aliases import TeamInfo

TEAM_REGISTRY: list[TeamInfo] = [
    TeamInfo(
        name='Arizona Cardinals',
        league_slug='football/nfl',
        espn_id='22',
        abbreviation='ARI',
        aliases=('ari', 'arizona cardinals', 'cardinals',),
    ),
    TeamInfo(
        name='Atlanta Falcons',
        league_slug='football/nfl',
        espn_id='1',
        abbreviation='ATL',
        aliases=('atl', 'atlanta falcons', 'falcons',),
    ),
    TeamInfo(
        name='Baltimore Ravens',
        league_slug='football/nfl',
        espn_id='33',
        abbreviation='BAL',
        aliases=('bal', 'baltimore ravens', 'ravens',),
    ),
    TeamInfo(
        name='Buffalo Bills',
        league_slug='football/nfl',
        espn_id='2',
        abbreviation='BUF',
        aliases=('bills', 'buf', 'buffalo bills',),
    ),
    TeamInfo(
        name='Carolina Panthers',
        league_slug='football/nfl',
        espn_id='29',
        abbreviation='CAR',
        aliases=('car', 'carolina panthers', 'panthers',),
    ),
    TeamInfo(
        name='Chicago Bears',
        league_slug='football/nfl',
        espn_id='3',
        abbreviation='CHI',
        aliases=('bears', 'chi', 'chicago bears',),
    ),
    TeamInfo(
        name='Cincinnati Bengals',
        league_slug='football/nfl',
        espn_id='4',
        abbreviation='CIN',
        aliases=('bengals', 'cin', 'cincinnati bengals',),
    ),
    TeamInfo(
        name='Cleveland Browns',
        league_slug='football/nfl',
        espn_id='5',
        abbreviation='CLE',
        aliases=('browns', 'cle', 'cleveland browns',),
    ),
    TeamInfo(
        name='Dallas Cowboys',
        league_slug='football/nfl',
        espn_id='6',
        abbreviation='DAL',
        aliases=('cowboys', 'dal', 'dallas cowboys',),
    ),
    TeamInfo(
        name='Denver Broncos',
        league_slug='football/nfl',
        espn_id='7',
        abbreviation='DEN',
        aliases=('broncos', 'den', 'denver broncos',),
    ),
    TeamInfo(
        name='Detroit Lions',
        league_slug='football/nfl',
        espn_id='8',
        abbreviation='DET',
        aliases=('det', 'detroit lions', 'lions',),
    ),
    TeamInfo(
        name='Green Bay Packers',
        league_slug='football/nfl',
        espn_id='9',
        abbreviation='GB',
        aliases=('gb', 'green bay packers', 'packers',),
    ),
    TeamInfo(
        name='Houston Texans',
        league_slug='football/nfl',
        espn_id='34',
        abbreviation='HOU',
        aliases=('hou', 'houston texans', 'texans',),
    ),
    TeamInfo(
        name='Indianapolis Colts',
        league_slug='football/nfl',
        espn_id='11',
        abbreviation='IND',
        aliases=('colts', 'ind', 'indianapolis colts',),
    ),
    TeamInfo(
        name='Jacksonville Jaguars',
        league_slug='football/nfl',
        espn_id='30',
        abbreviation='JAX',
        aliases=('jacksonville jaguars', 'jaguars', 'jax',),
    ),
    TeamInfo(
        name='Kansas City Chiefs',
        league_slug='football/nfl',
        espn_id='12',
        abbreviation='KC',
        aliases=('chiefs', 'kansas city chiefs', 'kc',),
    ),
    TeamInfo(
        name='Las Vegas Raiders',
        league_slug='football/nfl',
        espn_id='13',
        abbreviation='LV',
        aliases=('las vegas raiders', 'lv', 'raiders',),
    ),
    TeamInfo(
        name='Los Angeles Chargers',
        league_slug='football/nfl',
        espn_id='24',
        abbreviation='LAC',
        aliases=('chargers', 'lac', 'los angeles chargers',),
    ),
    TeamInfo(
        name='Los Angeles Rams',
        league_slug='football/nfl',
        espn_id='14',
        abbreviation='LAR',
        aliases=('lar', 'los angeles rams', 'rams',),
    ),
    TeamInfo(
        name='Miami Dolphins',
        league_slug='football/nfl',
        espn_id='15',
        abbreviation='MIA',
        aliases=('dolphins', 'mia', 'miami dolphins',),
    ),
    TeamInfo(
        name='Minnesota Vikings',
        league_slug='football/nfl',
        espn_id='16',
        abbreviation='MIN',
        aliases=('min', 'minnesota vikings', 'vikings',),
    ),
    TeamInfo(
        name='New England Patriots',
        league_slug='football/nfl',
        espn_id='17',
        abbreviation='NE',
        aliases=('ne', 'new england patriots', 'patriots',),
    ),
    TeamInfo(
        name='New Orleans Saints',
        league_slug='football/nfl',
        espn_id='18',
        abbreviation='NO',
        aliases=('new orleans saints', 'no', 'saints',),
    ),
    TeamInfo(
        name='New York Giants',
        league_slug='football/nfl',
        espn_id='19',
        abbreviation='NYG',
        aliases=('giants', 'new york giants', 'nyg',),
    ),
    TeamInfo(
        name='New York Jets',
        league_slug='football/nfl',
        espn_id='20',
        abbreviation='NYJ',
        aliases=('jets', 'new york jets', 'nyj',),
    ),
    TeamInfo(
        name='Philadelphia Eagles',
        league_slug='football/nfl',
        espn_id='21',
        abbreviation='PHI',
        aliases=('eagles', 'phi', 'philadelphia eagles',),
    ),
    TeamInfo(
        name='Pittsburgh Steelers',
        league_slug='football/nfl',
        espn_id='23',
        abbreviation='PIT',
        aliases=('pit', 'pittsburgh steelers', 'steelers',),
    ),
    TeamInfo(
        name='San Francisco 49ers',
        league_slug='football/nfl',
        espn_id='25',
        abbreviation='SF',
        aliases=('49ers', 'san francisco 49ers', 'sf',),
    ),
    TeamInfo(
        name='Seattle Seahawks',
        league_slug='football/nfl',
        espn_id='26',
        abbreviation='SEA',
        aliases=('sea', 'seahawks', 'seattle seahawks',),
    ),
    TeamInfo(
        name='Tampa Bay Buccaneers',
        league_slug='football/nfl',
        espn_id='27',
        abbreviation='TB',
        aliases=('buccaneers', 'tampa bay buccaneers', 'tb',),
    ),
    TeamInfo(
        name='Tennessee Titans',
        league_slug='football/nfl',
        espn_id='10',
        abbreviation='TEN',
        aliases=('ten', 'tennessee titans', 'titans',),
    ),
    TeamInfo(
        name='Washington Commanders',
        league_slug='football/nfl',
        espn_id='28',
        abbreviation='WSH',
        aliases=('commanders', 'washington commanders', 'wsh',),
    ),
    TeamInfo(
        name='Atlanta Hawks',
        league_slug='basketball/nba',
        espn_id='1',
        abbreviation='ATL',
        aliases=('atl', 'atlanta', 'atlanta hawks', 'hawks',),
    ),
    TeamInfo(
        name='Boston Celtics',
        league_slug='basketball/nba',
        espn_id='2',
        abbreviation='BOS',
        aliases=('bos', 'boston', 'boston celtics', 'celtics',),
    ),
    TeamInfo(
        name='Brooklyn Nets',
        league_slug='basketball/nba',
        espn_id='17',
        abbreviation='BKN',
        aliases=('bkn', 'brooklyn', 'brooklyn nets', 'nets',),
    ),
    TeamInfo(
        name='Charlotte Hornets',
        league_slug='basketball/nba',
        espn_id='30',
        abbreviation='CHA',
        aliases=('cha', 'charlotte', 'charlotte hornets', 'hornets',),
    ),
    TeamInfo(
        name='Chicago Bulls',
        league_slug='basketball/nba',
        espn_id='4',
        abbreviation='CHI',
        aliases=('bulls', 'chi', 'chicago', 'chicago bulls',),
    ),
    TeamInfo(
        name='Cleveland Cavaliers',
        league_slug='basketball/nba',
        espn_id='5',
        abbreviation='CLE',
        aliases=('cavaliers', 'cle', 'cleveland', 'cleveland cavaliers',),
    ),
    TeamInfo(
        name='Dallas Mavericks',
        league_slug='basketball/nba',
        espn_id='6',
        abbreviation='DAL',
        aliases=('dal', 'dallas', 'dallas mavericks', 'mavericks',),
    ),
    TeamInfo(
        name='Denver Nuggets',
        league_slug='basketball/nba',
        espn_id='7',
        abbreviation='DEN',
        aliases=('den', 'denver', 'denver nuggets', 'nuggets',),
    ),
    TeamInfo(
        name='Detroit Pistons',
        league_slug='basketball/nba',
        espn_id='8',
        abbreviation='DET',
        aliases=('det', 'detroit', 'detroit pistons', 'pistons',),
    ),
    TeamInfo(
        name='Golden State Warriors',
        league_slug='basketball/nba',
        espn_id='9',
        abbreviation='GS',
        aliases=('golden state', 'golden state warriors', 'gs', 'warriors',),
    ),
    TeamInfo(
        name='Houston Rockets',
        league_slug='basketball/nba',
        espn_id='10',
        abbreviation='HOU',
        aliases=('hou', 'houston', 'houston rockets', 'rockets',),
    ),
    TeamInfo(
        name='Indiana Pacers',
        league_slug='basketball/nba',
        espn_id='11',
        abbreviation='IND',
        aliases=('ind', 'indiana', 'indiana pacers', 'pacers',),
    ),
    TeamInfo(
        name='LA Clippers',
        league_slug='basketball/nba',
        espn_id='12',
        abbreviation='LAC',
        aliases=('clippers', 'la', 'la clippers', 'lac',),
    ),
    TeamInfo(
        name='Los Angeles Lakers',
        league_slug='basketball/nba',
        espn_id='13',
        abbreviation='LAL',
        aliases=('lakers', 'lal', 'los angeles', 'los angeles lakers',),
    ),
    TeamInfo(
        name='Memphis Grizzlies',
        league_slug='basketball/nba',
        espn_id='29',
        abbreviation='MEM',
        aliases=('grizzlies', 'mem', 'memphis', 'memphis grizzlies',),
    ),
    TeamInfo(
        name='Miami Heat',
        league_slug='basketball/nba',
        espn_id='14',
        abbreviation='MIA',
        aliases=('heat', 'mia', 'miami', 'miami heat',),
    ),
    TeamInfo(
        name='Milwaukee Bucks',
        league_slug='basketball/nba',
        espn_id='15',
        abbreviation='MIL',
        aliases=('bucks', 'mil', 'milwaukee', 'milwaukee bucks',),
    ),
    TeamInfo(
        name='Minnesota Timberwolves',
        league_slug='basketball/nba',
        espn_id='16',
        abbreviation='MIN',
        aliases=('min', 'minnesota', 'minnesota timberwolves', 'timberwolves',),
    ),
    TeamInfo(
        name='New Orleans Pelicans',
        league_slug='basketball/nba',
        espn_id='3',
        abbreviation='NO',
        aliases=('new orleans', 'new orleans pelicans', 'no', 'pelicans',),
    ),
    TeamInfo(
        name='New York Knicks',
        league_slug='basketball/nba',
        espn_id='18',
        abbreviation='NY',
        aliases=('knicks', 'new york', 'new york knicks', 'ny',),
    ),
    TeamInfo(
        name='Oklahoma City Thunder',
        league_slug='basketball/nba',
        espn_id='25',
        abbreviation='OKC',
        aliases=('okc', 'oklahoma city', 'oklahoma city thunder', 'thunder',),
    ),
    TeamInfo(
        name='Orlando Magic',
        league_slug='basketball/nba',
        espn_id='19',
        abbreviation='ORL',
        aliases=('magic', 'orl', 'orlando', 'orlando magic',),
    ),
    TeamInfo(
        name='Philadelphia 76ers',
        league_slug='basketball/nba',
        espn_id='20',
        abbreviation='PHI',
        aliases=('76ers', 'phi', 'philadelphia', 'philadelphia 76ers',),
    ),
    TeamInfo(
        name='Phoenix Suns',
        league_slug='basketball/nba',
        espn_id='21',
        abbreviation='PHX',
        aliases=('phoenix', 'phoenix suns', 'phx', 'suns',),
    ),
    TeamInfo(
        name='Portland Trail Blazers',
        league_slug='basketball/nba',
        espn_id='22',
        abbreviation='POR',
        aliases=('por', 'portland', 'portland trail blazers', 'trail blazers',),
    ),
    TeamInfo(
        name='Sacramento Kings',
        league_slug='basketball/nba',
        espn_id='23',
        abbreviation='SAC',
        aliases=('kings', 'sac', 'sacramento', 'sacramento kings',),
    ),
    TeamInfo(
        name='San Antonio Spurs',
        league_slug='basketball/nba',
        espn_id='24',
        abbreviation='SA',
        aliases=('sa', 'san antonio', 'san antonio spurs', 'spurs',),
    ),
    TeamInfo(
        name='Toronto Raptors',
        league_slug='basketball/nba',
        espn_id='28',
        abbreviation='TOR',
        aliases=('raptors', 'tor', 'toronto', 'toronto raptors',),
    ),
    TeamInfo(
        name='Utah Jazz',
        league_slug='basketball/nba',
        espn_id='26',
        abbreviation='UTAH',
        aliases=('jazz', 'utah', 'utah jazz',),
    ),
    TeamInfo(
        name='Washington Wizards',
        league_slug='basketball/nba',
        espn_id='27',
        abbreviation='WSH',
        aliases=('washington', 'washington wizards', 'wizards', 'wsh',),
    ),
    TeamInfo(
        name='Arizona Diamondbacks',
        league_slug='baseball/mlb',
        espn_id='29',
        abbreviation='ARI',
        aliases=('ari', 'arizona', 'arizona diamondbacks', 'diamondbacks',),
    ),
    TeamInfo(
        name='Athletics',
        league_slug='baseball/mlb',
        espn_id='11',
        abbreviation='ATH',
        aliases=('ath', 'athletics',),
    ),
    TeamInfo(
        name='Atlanta Braves',
        league_slug='baseball/mlb',
        espn_id='15',
        abbreviation='ATL',
        aliases=('atl', 'atlanta', 'atlanta braves', 'braves',),
    ),
    TeamInfo(
        name='Baltimore Orioles',
        league_slug='baseball/mlb',
        espn_id='1',
        abbreviation='BAL',
        aliases=('bal', 'baltimore', 'baltimore orioles', 'orioles',),
    ),
    TeamInfo(
        name='Boston Red Sox',
        league_slug='baseball/mlb',
        espn_id='2',
        abbreviation='BOS',
        aliases=('bos', 'boston', 'boston red sox', 'red sox',),
    ),
    TeamInfo(
        name='Chicago Cubs',
        league_slug='baseball/mlb',
        espn_id='16',
        abbreviation='CHC',
        aliases=('chc', 'chicago', 'chicago cubs', 'cubs',),
    ),
    TeamInfo(
        name='Chicago White Sox',
        league_slug='baseball/mlb',
        espn_id='4',
        abbreviation='CHW',
        aliases=('chicago', 'chicago white sox', 'chw', 'white sox',),
    ),
    TeamInfo(
        name='Cincinnati Reds',
        league_slug='baseball/mlb',
        espn_id='17',
        abbreviation='CIN',
        aliases=('cin', 'cincinnati', 'cincinnati reds', 'reds',),
    ),
    TeamInfo(
        name='Cleveland Guardians',
        league_slug='baseball/mlb',
        espn_id='5',
        abbreviation='CLE',
        aliases=('cle', 'cleveland', 'cleveland guardians', 'guardians',),
    ),
    TeamInfo(
        name='Colorado Rockies',
        league_slug='baseball/mlb',
        espn_id='27',
        abbreviation='COL',
        aliases=('col', 'colorado', 'colorado rockies', 'rockies',),
    ),
    TeamInfo(
        name='Detroit Tigers',
        league_slug='baseball/mlb',
        espn_id='6',
        abbreviation='DET',
        aliases=('det', 'detroit', 'detroit tigers', 'tigers',),
    ),
    TeamInfo(
        name='Houston Astros',
        league_slug='baseball/mlb',
        espn_id='18',
        abbreviation='HOU',
        aliases=('astros', 'hou', 'houston', 'houston astros',),
    ),
    TeamInfo(
        name='Kansas City Royals',
        league_slug='baseball/mlb',
        espn_id='7',
        abbreviation='KC',
        aliases=('kansas city', 'kansas city royals', 'kc', 'royals',),
    ),
    TeamInfo(
        name='Los Angeles Angels',
        league_slug='baseball/mlb',
        espn_id='3',
        abbreviation='LAA',
        aliases=('angels', 'laa', 'los angeles', 'los angeles angels',),
    ),
    TeamInfo(
        name='Los Angeles Dodgers',
        league_slug='baseball/mlb',
        espn_id='19',
        abbreviation='LAD',
        aliases=('dodgers', 'lad', 'los angeles', 'los angeles dodgers',),
    ),
    TeamInfo(
        name='Miami Marlins',
        league_slug='baseball/mlb',
        espn_id='28',
        abbreviation='MIA',
        aliases=('marlins', 'mia', 'miami', 'miami marlins',),
    ),
    TeamInfo(
        name='Milwaukee Brewers',
        league_slug='baseball/mlb',
        espn_id='8',
        abbreviation='MIL',
        aliases=('brewers', 'mil', 'milwaukee', 'milwaukee brewers',),
    ),
    TeamInfo(
        name='Minnesota Twins',
        league_slug='baseball/mlb',
        espn_id='9',
        abbreviation='MIN',
        aliases=('min', 'minnesota', 'minnesota twins', 'twins',),
    ),
    TeamInfo(
        name='New York Mets',
        league_slug='baseball/mlb',
        espn_id='21',
        abbreviation='NYM',
        aliases=('mets', 'new york', 'new york mets', 'nym',),
    ),
    TeamInfo(
        name='New York Yankees',
        league_slug='baseball/mlb',
        espn_id='10',
        abbreviation='NYY',
        aliases=('new york', 'new york yankees', 'nyy', 'yankees',),
    ),
    TeamInfo(
        name='Philadelphia Phillies',
        league_slug='baseball/mlb',
        espn_id='22',
        abbreviation='PHI',
        aliases=('phi', 'philadelphia', 'philadelphia phillies', 'phillies',),
    ),
    TeamInfo(
        name='Pittsburgh Pirates',
        league_slug='baseball/mlb',
        espn_id='23',
        abbreviation='PIT',
        aliases=('pirates', 'pit', 'pittsburgh', 'pittsburgh pirates',),
    ),
    TeamInfo(
        name='San Diego Padres',
        league_slug='baseball/mlb',
        espn_id='25',
        abbreviation='SD',
        aliases=('padres', 'san diego', 'san diego padres', 'sd',),
    ),
    TeamInfo(
        name='San Francisco Giants',
        league_slug='baseball/mlb',
        espn_id='26',
        abbreviation='SF',
        aliases=('giants', 'san francisco', 'san francisco giants', 'sf',),
    ),
    TeamInfo(
        name='Seattle Mariners',
        league_slug='baseball/mlb',
        espn_id='12',
        abbreviation='SEA',
        aliases=('mariners', 'sea', 'seattle', 'seattle mariners',),
    ),
    TeamInfo(
        name='St. Louis Cardinals',
        league_slug='baseball/mlb',
        espn_id='24',
        abbreviation='STL',
        aliases=('cardinals', 'st. louis', 'st. louis cardinals', 'stl',),
    ),
    TeamInfo(
        name='Tampa Bay Rays',
        league_slug='baseball/mlb',
        espn_id='30',
        abbreviation='TB',
        aliases=('rays', 'tampa bay', 'tampa bay rays', 'tb',),
    ),
    TeamInfo(
        name='Texas Rangers',
        league_slug='baseball/mlb',
        espn_id='13',
        abbreviation='TEX',
        aliases=('rangers', 'tex', 'texas', 'texas rangers',),
    ),
    TeamInfo(
        name='Toronto Blue Jays',
        league_slug='baseball/mlb',
        espn_id='14',
        abbreviation='TOR',
        aliases=('blue jays', 'tor', 'toronto', 'toronto blue jays',),
    ),
    TeamInfo(
        name='Washington Nationals',
        league_slug='baseball/mlb',
        espn_id='20',
        abbreviation='WSH',
        aliases=('nationals', 'washington', 'washington nationals', 'wsh',),
    ),
    TeamInfo(
        name='Anaheim Ducks',
        league_slug='hockey/nhl',
        espn_id='25',
        abbreviation='ANA',
        aliases=('ana', 'anaheim', 'anaheim ducks', 'ducks',),
    ),
    TeamInfo(
        name='Boston Bruins',
        league_slug='hockey/nhl',
        espn_id='1',
        abbreviation='BOS',
        aliases=('bos', 'boston', 'boston bruins', 'bruins',),
    ),
    TeamInfo(
        name='Buffalo Sabres',
        league_slug='hockey/nhl',
        espn_id='2',
        abbreviation='BUF',
        aliases=('buf', 'buffalo', 'buffalo sabres', 'sabres',),
    ),
    TeamInfo(
        name='Calgary Flames',
        league_slug='hockey/nhl',
        espn_id='3',
        abbreviation='CGY',
        aliases=('calgary', 'calgary flames', 'cgy', 'flames',),
    ),
    TeamInfo(
        name='Carolina Hurricanes',
        league_slug='hockey/nhl',
        espn_id='7',
        abbreviation='CAR',
        aliases=('car', 'carolina', 'carolina hurricanes', 'hurricanes',),
    ),
    TeamInfo(
        name='Chicago Blackhawks',
        league_slug='hockey/nhl',
        espn_id='4',
        abbreviation='CHI',
        aliases=('blackhawks', 'chi', 'chicago', 'chicago blackhawks',),
    ),
    TeamInfo(
        name='Colorado Avalanche',
        league_slug='hockey/nhl',
        espn_id='17',
        abbreviation='COL',
        aliases=('avalanche', 'col', 'colorado', 'colorado avalanche',),
    ),
    TeamInfo(
        name='Columbus Blue Jackets',
        league_slug='hockey/nhl',
        espn_id='29',
        abbreviation='CBJ',
        aliases=('blue jackets', 'cbj', 'columbus', 'columbus blue jackets',),
    ),
    TeamInfo(
        name='Dallas Stars',
        league_slug='hockey/nhl',
        espn_id='9',
        abbreviation='DAL',
        aliases=('dal', 'dallas', 'dallas stars', 'stars',),
    ),
    TeamInfo(
        name='Detroit Red Wings',
        league_slug='hockey/nhl',
        espn_id='5',
        abbreviation='DET',
        aliases=('det', 'detroit', 'detroit red wings', 'red wings',),
    ),
    TeamInfo(
        name='Edmonton Oilers',
        league_slug='hockey/nhl',
        espn_id='6',
        abbreviation='EDM',
        aliases=('edm', 'edmonton', 'edmonton oilers', 'oilers',),
    ),
    TeamInfo(
        name='Florida Panthers',
        league_slug='hockey/nhl',
        espn_id='26',
        abbreviation='FLA',
        aliases=('fla', 'florida', 'florida panthers', 'panthers',),
    ),
    TeamInfo(
        name='Los Angeles Kings',
        league_slug='hockey/nhl',
        espn_id='8',
        abbreviation='LA',
        aliases=('kings', 'la', 'los angeles', 'los angeles kings',),
    ),
    TeamInfo(
        name='Minnesota Wild',
        league_slug='hockey/nhl',
        espn_id='30',
        abbreviation='MIN',
        aliases=('min', 'minnesota', 'minnesota wild', 'wild',),
    ),
    TeamInfo(
        name='Montreal Canadiens',
        league_slug='hockey/nhl',
        espn_id='10',
        abbreviation='MTL',
        aliases=('canadiens', 'montreal', 'montreal canadiens', 'mtl',),
    ),
    TeamInfo(
        name='Nashville Predators',
        league_slug='hockey/nhl',
        espn_id='27',
        abbreviation='NSH',
        aliases=('nashville', 'nashville predators', 'nsh', 'predators',),
    ),
    TeamInfo(
        name='New Jersey Devils',
        league_slug='hockey/nhl',
        espn_id='11',
        abbreviation='NJ',
        aliases=('devils', 'new jersey', 'new jersey devils', 'nj',),
    ),
    TeamInfo(
        name='New York Islanders',
        league_slug='hockey/nhl',
        espn_id='12',
        abbreviation='NYI',
        aliases=('islanders', 'new york', 'new york islanders', 'nyi',),
    ),
    TeamInfo(
        name='New York Rangers',
        league_slug='hockey/nhl',
        espn_id='13',
        abbreviation='NYR',
        aliases=('new york', 'new york rangers', 'nyr', 'rangers',),
    ),
    TeamInfo(
        name='Ottawa Senators',
        league_slug='hockey/nhl',
        espn_id='14',
        abbreviation='OTT',
        aliases=('ott', 'ottawa', 'ottawa senators', 'senators',),
    ),
    TeamInfo(
        name='Philadelphia Flyers',
        league_slug='hockey/nhl',
        espn_id='15',
        abbreviation='PHI',
        aliases=('flyers', 'phi', 'philadelphia', 'philadelphia flyers',),
    ),
    TeamInfo(
        name='Pittsburgh Penguins',
        league_slug='hockey/nhl',
        espn_id='16',
        abbreviation='PIT',
        aliases=('penguins', 'pit', 'pittsburgh', 'pittsburgh penguins',),
    ),
    TeamInfo(
        name='San Jose Sharks',
        league_slug='hockey/nhl',
        espn_id='18',
        abbreviation='SJ',
        aliases=('san jose', 'san jose sharks', 'sharks', 'sj',),
    ),
    TeamInfo(
        name='Seattle Kraken',
        league_slug='hockey/nhl',
        espn_id='124292',
        abbreviation='SEA',
        aliases=('kraken', 'sea', 'seattle', 'seattle kraken',),
    ),
    TeamInfo(
        name='St. Louis Blues',
        league_slug='hockey/nhl',
        espn_id='19',
        abbreviation='STL',
        aliases=('blues', 'st. louis', 'st. louis blues', 'stl',),
    ),
    TeamInfo(
        name='Tampa Bay Lightning',
        league_slug='hockey/nhl',
        espn_id='20',
        abbreviation='TB',
        aliases=('lightning', 'tampa bay', 'tampa bay lightning', 'tb',),
    ),
    TeamInfo(
        name='Toronto Maple Leafs',
        league_slug='hockey/nhl',
        espn_id='21',
        abbreviation='TOR',
        aliases=('maple leafs', 'tor', 'toronto', 'toronto maple leafs',),
    ),
    TeamInfo(
        name='Utah Mammoth',
        league_slug='hockey/nhl',
        espn_id='129764',
        abbreviation='UTAH',
        aliases=('mammoth', 'utah', 'utah mammoth',),
    ),
    TeamInfo(
        name='Vancouver Canucks',
        league_slug='hockey/nhl',
        espn_id='22',
        abbreviation='VAN',
        aliases=('canucks', 'van', 'vancouver', 'vancouver canucks',),
    ),
    TeamInfo(
        name='Vegas Golden Knights',
        league_slug='hockey/nhl',
        espn_id='37',
        abbreviation='VGK',
        aliases=('golden knights', 'vegas', 'vegas golden knights', 'vgk',),
    ),
    TeamInfo(
        name='Washington Capitals',
        league_slug='hockey/nhl',
        espn_id='23',
        abbreviation='WSH',
        aliases=('capitals', 'washington', 'washington capitals', 'wsh',),
    ),
    TeamInfo(
        name='Winnipeg Jets',
        league_slug='hockey/nhl',
        espn_id='28',
        abbreviation='WPG',
        aliases=('jets', 'winnipeg', 'winnipeg jets', 'wpg',),
    ),
    TeamInfo(
        name='AFC Bournemouth',
        league_slug='soccer/eng.1',
        espn_id='349',
        abbreviation='BOU',
        aliases=('afc bournemouth', 'bou', 'bournemouth',),
    ),
    TeamInfo(
        name='Arsenal',
        league_slug='soccer/eng.1',
        espn_id='359',
        abbreviation='ARS',
        aliases=('ars', 'arsenal', 'gunners',),
    ),
    TeamInfo(
        name='Aston Villa',
        league_slug='soccer/eng.1',
        espn_id='362',
        abbreviation='AVL',
        aliases=('aston villa', 'avl',),
    ),
    TeamInfo(
        name='Brentford',
        league_slug='soccer/eng.1',
        espn_id='337',
        abbreviation='BRE',
        aliases=('bre', 'brentford',),
    ),
    TeamInfo(
        name='Brighton & Hove Albion',
        league_slug='soccer/eng.1',
        espn_id='331',
        abbreviation='BHA',
        aliases=('bha', 'brighton', 'brighton & hove albion', 'seagulls',),
    ),
    TeamInfo(
        name='Burnley',
        league_slug='soccer/eng.1',
        espn_id='379',
        abbreviation='BUR',
        aliases=('bur', 'burnley',),
    ),
    TeamInfo(
        name='Chelsea',
        league_slug='soccer/eng.1',
        espn_id='363',
        abbreviation='CHE',
        aliases=('blues', 'che', 'chelsea',),
    ),
    TeamInfo(
        name='Crystal Palace',
        league_slug='soccer/eng.1',
        espn_id='384',
        abbreviation='CRY',
        aliases=('c palace', 'cry', 'crystal palace', 'eagles',),
    ),
    TeamInfo(
        name='Everton',
        league_slug='soccer/eng.1',
        espn_id='368',
        abbreviation='EVE',
        aliases=('eve', 'everton', 'toffees',),
    ),
    TeamInfo(
        name='Fulham',
        league_slug='soccer/eng.1',
        espn_id='370',
        abbreviation='FUL',
        aliases=('ful', 'fulham',),
    ),
    TeamInfo(
        name='Leeds United',
        league_slug='soccer/eng.1',
        espn_id='357',
        abbreviation='LEE',
        aliases=('lee', 'leeds', 'leeds united',),
    ),
    TeamInfo(
        name='Liverpool',
        league_slug='soccer/eng.1',
        espn_id='364',
        abbreviation='LIV',
        aliases=('liv', 'liverpool', 'reds',),
    ),
    TeamInfo(
        name='Manchester City',
        league_slug='soccer/eng.1',
        espn_id='382',
        abbreviation='MNC',
        aliases=('man city', 'manchester city', 'mnc', 'sky blues',),
    ),
    TeamInfo(
        name='Manchester United',
        league_slug='soccer/eng.1',
        espn_id='360',
        abbreviation='MAN',
        aliases=('man', 'man united', 'manchester united', 'red devils',),
    ),
    TeamInfo(
        name='Newcastle United',
        league_slug='soccer/eng.1',
        espn_id='361',
        abbreviation='NEW',
        aliases=('magpies/toon', 'new', 'newcastle', 'newcastle united',),
    ),
    TeamInfo(
        name='Nottingham Forest',
        league_slug='soccer/eng.1',
        espn_id='393',
        abbreviation='NFO',
        aliases=('nfo', 'nottingham f.', 'nottingham forest', 'nottm forest',),
    ),
    TeamInfo(
        name='Sunderland',
        league_slug='soccer/eng.1',
        espn_id='366',
        abbreviation='SUN',
        aliases=('black cats/wearsiders', 'sun', 'sunderland',),
    ),
    TeamInfo(
        name='Tottenham Hotspur',
        league_slug='soccer/eng.1',
        espn_id='367',
        abbreviation='TOT',
        aliases=('spurs', 'tot', 'tottenham hotspur',),
    ),
    TeamInfo(
        name='West Ham United',
        league_slug='soccer/eng.1',
        espn_id='371',
        abbreviation='WHU',
        aliases=('hammers/iron', 'west ham', 'west ham united', 'whu',),
    ),
    TeamInfo(
        name='Wolverhampton Wanderers',
        league_slug='soccer/eng.1',
        espn_id='380',
        abbreviation='WOL',
        aliases=('wol', 'wolverhampton wanderers', 'wolves',),
    ),
    TeamInfo(
        name='Atlanta United FC',
        league_slug='soccer/usa.1',
        espn_id='18418',
        abbreviation='ATL',
        aliases=('atl', 'atlanta', 'atlanta united fc',),
    ),
    TeamInfo(
        name='Austin FC',
        league_slug='soccer/usa.1',
        espn_id='20906',
        abbreviation='ATX',
        aliases=('atx', 'austin', 'austin fc',),
    ),
    TeamInfo(
        name='CF Montréal',
        league_slug='soccer/usa.1',
        espn_id='9720',
        abbreviation='MTL',
        aliases=('cf montréal', 'impact', 'mtl',),
    ),
    TeamInfo(
        name='Charlotte FC',
        league_slug='soccer/usa.1',
        espn_id='21300',
        abbreviation='CLT',
        aliases=('charlotte', 'charlotte fc', 'clt',),
    ),
    TeamInfo(
        name='Chicago Fire FC',
        league_slug='soccer/usa.1',
        espn_id='182',
        abbreviation='CHI',
        aliases=('chi', 'chicago', 'chicago fire fc', 'fire',),
    ),
    TeamInfo(
        name='Colorado Rapids',
        league_slug='soccer/usa.1',
        espn_id='184',
        abbreviation='COL',
        aliases=('col', 'colorado', 'colorado rapids', 'rapids',),
    ),
    TeamInfo(
        name='Columbus Crew',
        league_slug='soccer/usa.1',
        espn_id='183',
        abbreviation='CLB',
        aliases=('clb', 'columbus', 'columbus crew', 'crew',),
    ),
    TeamInfo(
        name='D.C. United',
        league_slug='soccer/usa.1',
        espn_id='193',
        abbreviation='DC',
        aliases=('d.c. united', 'dc', 'united',),
    ),
    TeamInfo(
        name='FC Cincinnati',
        league_slug='soccer/usa.1',
        espn_id='18267',
        abbreviation='CIN',
        aliases=('cin', 'cincinnati', 'fc cincinnati',),
    ),
    TeamInfo(
        name='FC Dallas',
        league_slug='soccer/usa.1',
        espn_id='185',
        abbreviation='DAL',
        aliases=('dal', 'dallas', 'fc dallas',),
    ),
    TeamInfo(
        name='Houston Dynamo FC',
        league_slug='soccer/usa.1',
        espn_id='6077',
        abbreviation='HOU',
        aliases=('dynamo', 'hou', 'houston', 'houston dynamo fc',),
    ),
    TeamInfo(
        name='Inter Miami CF',
        league_slug='soccer/usa.1',
        espn_id='20232',
        abbreviation='MIA',
        aliases=('inter miami cf', 'mia', 'miami',),
    ),
    TeamInfo(
        name='LA Galaxy',
        league_slug='soccer/usa.1',
        espn_id='187',
        abbreviation='LA',
        aliases=('galaxy', 'la', 'la galaxy',),
    ),
    TeamInfo(
        name='LAFC',
        league_slug='soccer/usa.1',
        espn_id='18966',
        abbreviation='LAFC',
        aliases=('lafc',),
    ),
    TeamInfo(
        name='Minnesota United FC',
        league_slug='soccer/usa.1',
        espn_id='17362',
        abbreviation='MIN',
        aliases=('min', 'minnesota', 'minnesota united fc',),
    ),
    TeamInfo(
        name='Nashville SC',
        league_slug='soccer/usa.1',
        espn_id='18986',
        abbreviation='NSH',
        aliases=('nashville', 'nashville sc', 'nsh',),
    ),
    TeamInfo(
        name='New England Revolution',
        league_slug='soccer/usa.1',
        espn_id='189',
        abbreviation='NE',
        aliases=('ne', 'new england', 'new england revolution', 'revolution',),
    ),
    TeamInfo(
        name='New York City FC',
        league_slug='soccer/usa.1',
        espn_id='17606',
        abbreviation='NYC',
        aliases=('new york city fc', 'nyc', 'nyc fc', 'nycfc',),
    ),
    TeamInfo(
        name='Orlando City SC',
        league_slug='soccer/usa.1',
        espn_id='12011',
        abbreviation='ORL',
        aliases=('orl', 'orlando', 'orlando city sc',),
    ),
    TeamInfo(
        name='Philadelphia Union',
        league_slug='soccer/usa.1',
        espn_id='10739',
        abbreviation='PHI',
        aliases=('phi', 'philadelphia', 'philadelphia union', 'union',),
    ),
    TeamInfo(
        name='Portland Timbers',
        league_slug='soccer/usa.1',
        espn_id='9723',
        abbreviation='POR',
        aliases=('por', 'portland', 'portland timbers', 'timbers',),
    ),
    TeamInfo(
        name='Real Salt Lake',
        league_slug='soccer/usa.1',
        espn_id='4771',
        abbreviation='RSL',
        aliases=('real salt lake', 'rsl', 'salt lake',),
    ),
    TeamInfo(
        name='Red Bull New York',
        league_slug='soccer/usa.1',
        espn_id='190',
        abbreviation='RBNY',
        aliases=('rbny', 'red bull new york', 'red bull ny', 'red bulls',),
    ),
    TeamInfo(
        name='San Diego FC',
        league_slug='soccer/usa.1',
        espn_id='22529',
        abbreviation='SD',
        aliases=('san diego', 'san diego fc', 'sd',),
    ),
    TeamInfo(
        name='San Jose Earthquakes',
        league_slug='soccer/usa.1',
        espn_id='191',
        abbreviation='SJ',
        aliases=('earthquakes', 'san jose', 'san jose earthquakes', 'sj',),
    ),
    TeamInfo(
        name='Seattle Sounders FC',
        league_slug='soccer/usa.1',
        espn_id='9726',
        abbreviation='SEA',
        aliases=('sea', 'seattle', 'seattle sounders fc', 'sounders',),
    ),
    TeamInfo(
        name='Sporting Kansas City',
        league_slug='soccer/usa.1',
        espn_id='186',
        abbreviation='SKC',
        aliases=('kansas city', 'skc', 'sporting', 'sporting kansas city',),
    ),
    TeamInfo(
        name='St. Louis CITY SC',
        league_slug='soccer/usa.1',
        espn_id='21812',
        abbreviation='STL',
        aliases=('st. louis', 'st. louis city sc', 'stl',),
    ),
    TeamInfo(
        name='Toronto FC',
        league_slug='soccer/usa.1',
        espn_id='7318',
        abbreviation='TOR',
        aliases=('tor', 'toronto', 'toronto fc',),
    ),
    TeamInfo(
        name='Vancouver Whitecaps',
        league_slug='soccer/usa.1',
        espn_id='9727',
        abbreviation='VAN',
        aliases=('van', 'vancouver', 'vancouver whitecaps', 'whitecaps',),
    ),
    TeamInfo(
        name='Algeria',
        league_slug='soccer/fifa.world',
        espn_id='624',
        abbreviation='ALG',
        aliases=('alg', 'algeria',),
    ),
    TeamInfo(
        name='Argentina',
        league_slug='soccer/fifa.world',
        espn_id='202',
        abbreviation='ARG',
        aliases=('arg', 'argentina',),
    ),
    TeamInfo(
        name='Australia',
        league_slug='soccer/fifa.world',
        espn_id='628',
        abbreviation='AUS',
        aliases=('aus', 'australia',),
    ),
    TeamInfo(
        name='Austria',
        league_slug='soccer/fifa.world',
        espn_id='474',
        abbreviation='AUT',
        aliases=('austria', 'aut',),
    ),
    TeamInfo(
        name='Belgium',
        league_slug='soccer/fifa.world',
        espn_id='459',
        abbreviation='BEL',
        aliases=('bel', 'belgium',),
    ),
    TeamInfo(
        name='Bosnia-Herzegovina',
        league_slug='soccer/fifa.world',
        espn_id='452',
        abbreviation='BIH',
        aliases=('bih', 'bosnia-herz', 'bosnia-herzegovina',),
    ),
    TeamInfo(
        name='Brazil',
        league_slug='soccer/fifa.world',
        espn_id='205',
        abbreviation='BRA',
        aliases=('bra', 'brazil',),
    ),
    TeamInfo(
        name='Canada',
        league_slug='soccer/fifa.world',
        espn_id='206',
        abbreviation='CAN',
        aliases=('can', 'canada',),
    ),
    TeamInfo(
        name='Cape Verde',
        league_slug='soccer/fifa.world',
        espn_id='2597',
        abbreviation='CPV',
        aliases=('cape verde', 'cpv',),
    ),
    TeamInfo(
        name='Colombia',
        league_slug='soccer/fifa.world',
        espn_id='208',
        abbreviation='COL',
        aliases=('col', 'colombia',),
    ),
    TeamInfo(
        name='Congo DR',
        league_slug='soccer/fifa.world',
        espn_id='2850',
        abbreviation='COD',
        aliases=('cod', 'congo dr',),
    ),
    TeamInfo(
        name='Croatia',
        league_slug='soccer/fifa.world',
        espn_id='477',
        abbreviation='CRO',
        aliases=('cro', 'croatia',),
    ),
    TeamInfo(
        name='Curacao',
        league_slug='soccer/fifa.world',
        espn_id='11678',
        abbreviation='CUW',
        aliases=('curacao', 'cuw',),
    ),
    TeamInfo(
        name='Czechia',
        league_slug='soccer/fifa.world',
        espn_id='450',
        abbreviation='CZE',
        aliases=('cze', 'czechia',),
    ),
    TeamInfo(
        name='Ecuador',
        league_slug='soccer/fifa.world',
        espn_id='209',
        abbreviation='ECU',
        aliases=('ecu', 'ecuador',),
    ),
    TeamInfo(
        name='Egypt',
        league_slug='soccer/fifa.world',
        espn_id='2620',
        abbreviation='EGY',
        aliases=('egy', 'egypt',),
    ),
    TeamInfo(
        name='England',
        league_slug='soccer/fifa.world',
        espn_id='448',
        abbreviation='ENG',
        aliases=('eng', 'england',),
    ),
    TeamInfo(
        name='France',
        league_slug='soccer/fifa.world',
        espn_id='478',
        abbreviation='FRA',
        aliases=('fra', 'france',),
    ),
    TeamInfo(
        name='Germany',
        league_slug='soccer/fifa.world',
        espn_id='481',
        abbreviation='GER',
        aliases=('ger', 'germany',),
    ),
    TeamInfo(
        name='Ghana',
        league_slug='soccer/fifa.world',
        espn_id='4469',
        abbreviation='GHA',
        aliases=('gha', 'ghana',),
    ),
    TeamInfo(
        name='Haiti',
        league_slug='soccer/fifa.world',
        espn_id='2654',
        abbreviation='HAI',
        aliases=('hai', 'haiti',),
    ),
    TeamInfo(
        name='Iran',
        league_slug='soccer/fifa.world',
        espn_id='469',
        abbreviation='IRN',
        aliases=('iran', 'irn',),
    ),
    TeamInfo(
        name='Iraq',
        league_slug='soccer/fifa.world',
        espn_id='4375',
        abbreviation='IRQ',
        aliases=('iraq', 'irq',),
    ),
    TeamInfo(
        name='Ivory Coast',
        league_slug='soccer/fifa.world',
        espn_id='4789',
        abbreviation='CIV',
        aliases=('civ', 'ivory coast',),
    ),
    TeamInfo(
        name='Japan',
        league_slug='soccer/fifa.world',
        espn_id='627',
        abbreviation='JPN',
        aliases=('japan', 'jpn',),
    ),
    TeamInfo(
        name='Jordan',
        league_slug='soccer/fifa.world',
        espn_id='2917',
        abbreviation='JOR',
        aliases=('jor', 'jordan',),
    ),
    TeamInfo(
        name='Mexico',
        league_slug='soccer/fifa.world',
        espn_id='203',
        abbreviation='MEX',
        aliases=('mex', 'mexico',),
    ),
    TeamInfo(
        name='Morocco',
        league_slug='soccer/fifa.world',
        espn_id='2869',
        abbreviation='MAR',
        aliases=('mar', 'morocco',),
    ),
    TeamInfo(
        name='Netherlands',
        league_slug='soccer/fifa.world',
        espn_id='449',
        abbreviation='NED',
        aliases=('ned', 'netherlands',),
    ),
    TeamInfo(
        name='New Zealand',
        league_slug='soccer/fifa.world',
        espn_id='2666',
        abbreviation='NZL',
        aliases=('new zealand', 'nzl',),
    ),
    TeamInfo(
        name='Norway',
        league_slug='soccer/fifa.world',
        espn_id='464',
        abbreviation='NOR',
        aliases=('nor', 'norway',),
    ),
    TeamInfo(
        name='Panama',
        league_slug='soccer/fifa.world',
        espn_id='2659',
        abbreviation='PAN',
        aliases=('pan', 'panama',),
    ),
    TeamInfo(
        name='Paraguay',
        league_slug='soccer/fifa.world',
        espn_id='210',
        abbreviation='PAR',
        aliases=('par', 'paraguay',),
    ),
    TeamInfo(
        name='Portugal',
        league_slug='soccer/fifa.world',
        espn_id='482',
        abbreviation='POR',
        aliases=('por', 'portugal',),
    ),
    TeamInfo(
        name='Qatar',
        league_slug='soccer/fifa.world',
        espn_id='4398',
        abbreviation='QAT',
        aliases=('qat', 'qatar',),
    ),
    TeamInfo(
        name='Saudi Arabia',
        league_slug='soccer/fifa.world',
        espn_id='655',
        abbreviation='KSA',
        aliases=('ksa', 'saudi arabia',),
    ),
    TeamInfo(
        name='Scotland',
        league_slug='soccer/fifa.world',
        espn_id='580',
        abbreviation='SCO',
        aliases=('sco', 'scotland',),
    ),
    TeamInfo(
        name='Senegal',
        league_slug='soccer/fifa.world',
        espn_id='654',
        abbreviation='SEN',
        aliases=('sen', 'senegal',),
    ),
    TeamInfo(
        name='South Africa',
        league_slug='soccer/fifa.world',
        espn_id='467',
        abbreviation='RSA',
        aliases=('rsa', 'south africa',),
    ),
    TeamInfo(
        name='South Korea',
        league_slug='soccer/fifa.world',
        espn_id='451',
        abbreviation='KOR',
        aliases=('kor', 'south korea',),
    ),
    TeamInfo(
        name='Spain',
        league_slug='soccer/fifa.world',
        espn_id='164',
        abbreviation='ESP',
        aliases=('esp', 'spain',),
    ),
    TeamInfo(
        name='Sweden',
        league_slug='soccer/fifa.world',
        espn_id='466',
        abbreviation='SWE',
        aliases=('swe', 'sweden',),
    ),
    TeamInfo(
        name='Switzerland',
        league_slug='soccer/fifa.world',
        espn_id='475',
        abbreviation='SUI',
        aliases=('sui', 'switzerland',),
    ),
    TeamInfo(
        name='Tunisia',
        league_slug='soccer/fifa.world',
        espn_id='659',
        abbreviation='TUN',
        aliases=('tun', 'tunisia',),
    ),
    TeamInfo(
        name='Türkiye',
        league_slug='soccer/fifa.world',
        espn_id='465',
        abbreviation='TUR',
        aliases=('tur', 'türkiye',),
    ),
    TeamInfo(
        name='United States',
        league_slug='soccer/fifa.world',
        espn_id='660',
        abbreviation='USA',
        aliases=('united states', 'usa',),
    ),
    TeamInfo(
        name='Uruguay',
        league_slug='soccer/fifa.world',
        espn_id='212',
        abbreviation='URU',
        aliases=('uru', 'uruguay',),
    ),
    TeamInfo(
        name='Uzbekistan',
        league_slug='soccer/fifa.world',
        espn_id='2570',
        abbreviation='UZB',
        aliases=('uzb', 'uzbekistan',),
    ),
    TeamInfo(
        name='AS Monaco',
        league_slug='soccer/uefa.champions',
        espn_id='174',
        abbreviation='MON',
        aliases=('as monaco', 'mon', 'monaco',),
    ),
    TeamInfo(
        name='Ajax Amsterdam',
        league_slug='soccer/uefa.champions',
        espn_id='139',
        abbreviation='AJA',
        aliases=('aja', 'ajax', 'ajax amsterdam',),
    ),
    TeamInfo(
        name='Arsenal',
        league_slug='soccer/uefa.champions',
        espn_id='359',
        abbreviation='ARS',
        aliases=('ars', 'arsenal', 'gunners',),
    ),
    TeamInfo(
        name='Atalanta',
        league_slug='soccer/uefa.champions',
        espn_id='105',
        abbreviation='ATA',
        aliases=('ata', 'atalanta',),
    ),
    TeamInfo(
        name='Athletic Club',
        league_slug='soccer/uefa.champions',
        espn_id='93',
        abbreviation='ATH',
        aliases=('ath', 'athletic', 'athletic club',),
    ),
    TeamInfo(
        name='Atlético Madrid',
        league_slug='soccer/uefa.champions',
        espn_id='1068',
        abbreviation='ATM',
        aliases=('atlético', 'atlético madrid', 'atm',),
    ),
    TeamInfo(
        name='Barcelona',
        league_slug='soccer/uefa.champions',
        espn_id='83',
        abbreviation='BAR',
        aliases=('bar', 'barcelona', 'barça',),
    ),
    TeamInfo(
        name='Bayer Leverkusen',
        league_slug='soccer/uefa.champions',
        espn_id='131',
        abbreviation='B04',
        aliases=('b04', 'bayer leverkusen', 'leverkusen',),
    ),
    TeamInfo(
        name='Bayern Munich',
        league_slug='soccer/uefa.champions',
        espn_id='132',
        abbreviation='MUN',
        aliases=('bayern', 'bayern munich', 'mun',),
    ),
    TeamInfo(
        name='Benfica',
        league_slug='soccer/uefa.champions',
        espn_id='1929',
        abbreviation='SLB',
        aliases=('benfica', 'slb',),
    ),
    TeamInfo(
        name='Bodo/Glimt',
        league_slug='soccer/uefa.champions',
        espn_id='2980',
        abbreviation='BODO',
        aliases=('bodo', 'bodo/glimt',),
    ),
    TeamInfo(
        name='Borussia Dortmund',
        league_slug='soccer/uefa.champions',
        espn_id='124',
        abbreviation='DOR',
        aliases=('borussia dortmund', 'dor', 'dortmund',),
    ),
    TeamInfo(
        name='Chelsea',
        league_slug='soccer/uefa.champions',
        espn_id='363',
        abbreviation='CHE',
        aliases=('blues', 'che', 'chelsea',),
    ),
    TeamInfo(
        name='Club Brugge',
        league_slug='soccer/uefa.champions',
        espn_id='570',
        abbreviation='BRU',
        aliases=('bru', 'club brugge',),
    ),
    TeamInfo(
        name='Eintracht Frankfurt',
        league_slug='soccer/uefa.champions',
        espn_id='125',
        abbreviation='SGE',
        aliases=('eintracht frankfurt', 'frankfurt', 'sge',),
    ),
    TeamInfo(
        name='F.C. København',
        league_slug='soccer/uefa.champions',
        espn_id='909',
        abbreviation='KBH',
        aliases=('f.c. københavn', 'kbh', 'københavn',),
    ),
    TeamInfo(
        name='FK Qarabag',
        league_slug='soccer/uefa.champions',
        espn_id='10414',
        abbreviation='QAR',
        aliases=('fk qarabag', 'qar',),
    ),
    TeamInfo(
        name='Galatasaray',
        league_slug='soccer/uefa.champions',
        espn_id='432',
        abbreviation='GAL',
        aliases=('gal', 'galatasaray',),
    ),
    TeamInfo(
        name='Internazionale',
        league_slug='soccer/uefa.champions',
        espn_id='110',
        abbreviation='INT',
        aliases=('int', 'inter milan', 'internazionale',),
    ),
    TeamInfo(
        name='Juventus',
        league_slug='soccer/uefa.champions',
        espn_id='111',
        abbreviation='JUV',
        aliases=('juv', 'juventus',),
    ),
    TeamInfo(
        name='Kairat Almaty',
        league_slug='soccer/uefa.champions',
        espn_id='2528',
        abbreviation='KAI',
        aliases=('kai', 'kairat almaty',),
    ),
    TeamInfo(
        name='Liverpool',
        league_slug='soccer/uefa.champions',
        espn_id='364',
        abbreviation='LIV',
        aliases=('liv', 'liverpool', 'reds',),
    ),
    TeamInfo(
        name='Manchester City',
        league_slug='soccer/uefa.champions',
        espn_id='382',
        abbreviation='MNC',
        aliases=('man city', 'manchester city', 'mnc', 'sky blues',),
    ),
    TeamInfo(
        name='Marseille',
        league_slug='soccer/uefa.champions',
        espn_id='176',
        abbreviation='OLM',
        aliases=('marseille', 'olm',),
    ),
    TeamInfo(
        name='Napoli',
        league_slug='soccer/uefa.champions',
        espn_id='114',
        abbreviation='NAP',
        aliases=('nap', 'napoli',),
    ),
    TeamInfo(
        name='Newcastle United',
        league_slug='soccer/uefa.champions',
        espn_id='361',
        abbreviation='NEW',
        aliases=('magpies/toon', 'new', 'newcastle', 'newcastle united',),
    ),
    TeamInfo(
        name='Olympiacos',
        league_slug='soccer/uefa.champions',
        espn_id='435',
        abbreviation='OLY',
        aliases=('oly', 'olympiacos',),
    ),
    TeamInfo(
        name='PSV Eindhoven',
        league_slug='soccer/uefa.champions',
        espn_id='148',
        abbreviation='PSV',
        aliases=('psv', 'psv eindhoven',),
    ),
    TeamInfo(
        name='Pafos',
        league_slug='soccer/uefa.champions',
        espn_id='22281',
        abbreviation='PAF',
        aliases=('paf', 'pafos',),
    ),
    TeamInfo(
        name='Paris Saint-Germain',
        league_slug='soccer/uefa.champions',
        espn_id='160',
        abbreviation='PSG',
        aliases=('paris saint-germain', 'psg',),
    ),
    TeamInfo(
        name='Real Madrid',
        league_slug='soccer/uefa.champions',
        espn_id='86',
        abbreviation='RMA',
        aliases=('real madrid', 'rma',),
    ),
    TeamInfo(
        name='Slavia Prague',
        league_slug='soccer/uefa.champions',
        espn_id='494',
        abbreviation='SLP',
        aliases=('slavia prague', 'slp',),
    ),
    TeamInfo(
        name='Sporting CP',
        league_slug='soccer/uefa.champions',
        espn_id='2250',
        abbreviation='SCP',
        aliases=('scp', 'sporting', 'sporting cp',),
    ),
    TeamInfo(
        name='Tottenham Hotspur',
        league_slug='soccer/uefa.champions',
        espn_id='367',
        abbreviation='TOT',
        aliases=('spurs', 'tot', 'tottenham hotspur',),
    ),
    TeamInfo(
        name='Union St.-Gilloise',
        league_slug='soccer/uefa.champions',
        espn_id='5807',
        abbreviation='USG',
        aliases=('union sg', 'union st.-gilloise', 'usg',),
    ),
    TeamInfo(
        name='Villarreal',
        league_slug='soccer/uefa.champions',
        espn_id='102',
        abbreviation='VIL',
        aliases=('vil', 'villarreal',),
    ),
]
